[package]
name = "public-ip"
version = "0.1.1"
authors = ["avitex <avitex@wfxlabs.com>"]
edition = "2018"
description = "Find the public IP address of a device"
documentation = "https://docs.rs/public-ip"
homepage = "https://github.com/avitex/rust-public-ip"
repository = "https://github.com/avitex/rust-public-ip"
license = "MIT"

[badges]
travis-ci = { repository = "avitex/rust-public-ip", branch = "master" }

[features]
default = ["dns-resolver", "http-resolver"]
dns-resolver = ["tokio", "trust-dns-client", "trust-dns-proto", "once_cell"]
http-resolver = ["tokio", "http", "hyper", "regex", "once_cell"]

[dependencies]
futures = "0.3"

trust-dns-client = { version = "0.19", optional = true }
trust-dns-proto = { version = "0.19", optional = true }
once_cell = { version = "~1", optional = true }
hyper = { version = "0.13", optional = true }
http = { version = "0.2", optional = true }
regex = { version = "~1", optional = true }
tokio = { version = "1.0", features = ["rt-threaded"], optional = true }

[dev-dependencies]
async-std = "~1"